services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: nasgunawan/otonotif-app:latest
    container_name: otonotif-web
    expose:
      - "3000"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=file:./data/otonotif.db
    volumes:
      - otonotif-data:/app/data
    restart: always
    networks:
      - default
      - proxy-net

volumes:
  otonotif-data:

networks:
  proxy-net:
    external: true
